In [1]:
from tabula import read_pdf
from tabulate import tabulate
import pandas as pd

In [2]:
firstCry_pdf = read_pdf("1582693400232_1_0000717697_2020_02_26_10_31_13_AM.pdf", pages="all", multiple_tables=True)

Error importing jpype dependencies. Fallback to subprocess.
No module named 'jpype'
Got stderr: Feb 15, 2024 6:03:04 PM org.apache.pdfbox.pdmodel.font.PDSimpleFont toUnicode
WARNING: No Unicode mapping for .notdef (13) in font Helvetica-Bold
Feb 15, 2024 6:03:04 PM org.apache.pdfbox.pdmodel.font.PDSimpleFont toUnicode
WARNING: No Unicode mapping for .notdef (10) in font Helvetica-Bold
Feb 15, 2024 6:03:04 PM org.apache.pdfbox.pdmodel.font.PDSimpleFont toUnicode
WARNING: No Unicode mapping for .notdef (13) in font Helvetica
Feb 15, 2024 6:03:04 PM org.apache.pdfbox.pdmodel.font.PDSimpleFont toUnicode
WARNING: No Unicode mapping for .notdef (10) in font Helvetica
Feb 15, 2024 6:03:04 PM org.apache.pdfbox.rendering.Type1Glyph2D getPathForCharacterCode
WARNING: No glyph for code 13 (.notdef) in font Helvetica-Bold
Feb 15, 2024 6:03:04 PM org.apache.pdfbox.rendering.Type1Glyph2D getPathForCharacterCode
WARNING: No glyph for code 10 (.notdef) in font Helvetica-Bold
Feb 15, 2024 6:03:04 PM org.apache.pdfbox.rendering.Type1Glyph2D getPathForCharacterCode
WARNING: No glyph for code 13 (.notdef) in font Helvetica
Feb 15, 2024 6:03:04 PM org.apache.pdfbox.rendering.Type1Glyph2D getPathForCharacterCode
WARNING: No glyph for code 10 (.notdef) in font Helvetica
Feb 15, 2024 6:03:06 PM org.apache.pdfbox.rendering.Type1Glyph2D getPathForCharacterCode
WARNING: No glyph for code 13 (.notdef) in font Helvetica-Bold
Feb 15, 2024 6:03:06 PM org.apache.pdfbox.rendering.Type1Glyph2D getPathForCharacterCode
WARNING: No glyph for code 10 (.notdef) in font Helvetica-Bold
Feb 15, 2024 6:03:06 PM org.apache.pdfbox.rendering.Type1Glyph2D getPathForCharacterCode
WARNING: No glyph for code 13 (.notdef) in font Helvetica-Bold
Feb 15, 2024 6:03:06 PM org.apache.pdfbox.rendering.Type1Glyph2D getPathForCharacterCode
WARNING: No glyph for code 10 (.notdef) in font Helvetica-Bold
Feb 15, 2024 6:03:07 PM org.apache.pdfbox.rendering.Type1Glyph2D getPathForCharacterCode
WARNING: No glyph for code 13 (.notdef) in font Helvetica-Bold
Feb 15, 2024 6:03:07 PM org.apache.pdfbox.rendering.Type1Glyph2D getPathForCharacterCode
WARNING: No glyph for code 10 (.notdef) in font Helvetica-Bold

In [3]:
firstCry_pdf[0]

,Terril Impex India Pvt Ltd. (Vasundhara),Unnamed: 0,Unnamed: 1
0,Vendor Name: THE HIMALAYA DRUG COMPANY - GHAZI...,PONO:,AFC/20022020/462189
1,"Address: 95, ANAND INDUSTRIAL ESTATE, MOHAN NA...",PO Date:,20-02-2020
2,"201007, UP, GHAZIABAD, Uttar Pradesh, India - ...",NaN,NaN
3,Delivered By: THE HIMALAYA DRUG COMPANY - GHAZ...,Payment Terms:,Advance
4,"Address: 10, ANAND INDUSTRIAL ESTATE, MOHAN NA...",PO Expiry Date:-,20-02-2020
5,"201007, UP",GST No.:,09AADFT3025B1ZN
6,NaN,F & O:,0
7,Delivered To: Terril Impex India Pvt Ltd. (Vas...,GST No.:,09AAFCT1149K1Z3
8,Address:- D-1 SITE 4 SAHIBABAD INDUSTRIAL AREA...,NaN,NaN
9,"Pradesh, India - 201010",NaN,NaN

In [4]:
firstCry_table = pd.DataFrame(firstCry_pdf[1])

firstCry_table

,Sr.,HSN,FCID,Manufa,Style,Image,Product Product,Unnamed: 0,Brand,Siz,Col,MRP,Offer,Base,Tax,Landing,Bill,Fre,Total,Total.1
0,No.,Code,NaN,cturer,Code,NaN,Name Descript,NaN,Name,e,or,NaN,MRP,Cost,NaN,Rate,ed,e,Qty,Amount
1,NaN,NaN,NaN,NaN,NaN,NaN,ion,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Qty,Qty,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,.,NaN,NaN
3,1,9619,41948.0,8901138,70017,NaN,Himalay 8 to 14,NaN,Himalay,Lar,9F9,130.0,130.00,81.25,12.0,91.00,24,0,24,2184.00
4,NaN,NaN,4.0,831189,92,NaN,"a Herbal Kg, 9",NaN,a,ge,2B,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,"Baby pieces,",NaN,Babycar,NaN,E,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN,Diapers With anti,NaN,e,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,NaN,NaN,NaN,Large - 9 rash,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,NaN,NaN,NaN,NaN,NaN,Pieces shield,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,NaN,NaN,NaN,NaN,NaN,and,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,NaN,NaN,NaN,NaN,NaN,NaN,buttery,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,NaN,NaN,NaN,NaN,NaN,NaN,soft,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,NaN,NaN,NaN,NaN,NaN,NaN,inner,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,NaN,NaN,NaN,NaN,NaN,NaN,layer,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,2,9619,58630.0,8901138,70020,NaN,Himalay Upto 7,NaN,Himalay,Sm,9F9,650.0,650.00,406.25,12.0,455.00,24,0,24,10920.00
15,NaN,NaN,0.0,832698,48,NaN,"a Herbal kg, 0 to",NaN,a,all,2B,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,NaN,NaN,NaN,NaN,NaN,NaN,Baby 3,NaN,Babycar,NaN,E,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,NaN,NaN,NaN,NaN,NaN,NaN,"Diapers Months,",NaN,e,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,NaN,NaN,NaN,NaN,NaN,NaN,Small - Diapers,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,NaN,NaN,NaN,NaN,NaN,NaN,54 with,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,NaN,NaN,NaN,NaN,NaN,NaN,Pieces natural,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,NaN,NaN,NaN,NaN,NaN,NaN,anti rash,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,NaN,NaN,NaN,NaN,NaN,NaN,shield:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,NaN,NaN,NaN,NaN,NaN,NaN,Indian,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,NaN,NaN,NaN,NaN,NaN,NaN,Aloe and,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,NaN,NaN,NaN,NaN,NaN,NaN,Yashad,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,NaN,NaN,NaN,NaN,NaN,NaN,Bhasma,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,NaN,NaN,NaN,NaN,NaN,NaN,(Zinc,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,NaN,NaN,NaN,NaN,NaN,NaN,"Oxide),B",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,NaN,NaN,NaN,NaN,NaN,NaN,uttery,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,NaN,NaN,NaN,NaN,NaN,NaN,soft,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,NaN,NaN,NaN,NaN,NaN,NaN,inner,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,NaN,NaN,NaN,NaN,NaN,NaN,layer for,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,NaN,NaN,NaN,NaN,NaN,NaN,soft and,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,NaN,NaN,NaN,NaN,NaN,NaN,sensitive,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,NaN,NaN,NaN,NaN,NaN,NaN,skin,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
import pandas as pd
import numpy as np


for col in firstCry_table.columns.tolist():
    column = col
    for index in range(len(firstCry_table[col])):
        if not pd.isna(firstCry_table[col].iloc[index]):
            column += str(firstCry_table[col].iloc[index])
            firstCry_table[col].iloc[index] = np.nan
        else:
            break
    firstCry_table.rename(columns={col: column}, inplace=True)

C:\Users\TP_USER\AppData\Local\Temp\ipykernel_8336\1533519715.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  firstCry_table[col].iloc[index] = np.nan
C:\Users\TP_USER\AppData\Local\Temp\ipykernel_8336\1533519715.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  firstCry_table[col].iloc[index] = np.nan
C:\Users\TP_USER\AppData\Local\Temp\ipykernel_8336\1533519715.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  firstCry_table[col].iloc[index] = np.nan
C:\Users\TP_USER\AppData\Local\Temp\ipykernel_8336\1533519715.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  firstCry_table[col].iloc[index] = np.nan
C:\Users\TP_USER\AppData\Local\Temp\ipykernel_8336\1533519715.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  firstCry_table[col].iloc[index] = np.nan
C:\Users\TP_USER\AppData\Local\Temp\ipykernel_8336\1533519715.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  firstCry_table[col].iloc[index] = np.nan
C:\Users\TP_USER\AppData\Local\Temp\ipykernel_8336\1533519715.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  firstCry_table[col].iloc[index] = np.nan
C:\Users\TP_USER\AppData\Local\Temp\ipykernel_8336\1533519715.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  firstCry_table[col].iloc[index] = np.nan
C:\Users\TP_USER\AppData\Local\Temp\ipykernel_8336\1533519715.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  firstCry_table[col].iloc[index] = np.nan
C:\Users\TP_USER\AppData\Local\Temp\ipykernel_8336\1533519715.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  firstCry_table[col].iloc[index] = np.nan
C:\Users\TP_USER\AppData\Local\Temp\ipykernel_8336\1533519715.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  firstCry_table[col].iloc[index] = np.nan
C:\Users\TP_USER\AppData\Local\Temp\ipykernel_8336\1533519715.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  firstCry_table[col].iloc[index] = np.nan
C:\Users\TP_USER\AppData\Local\Temp\ipykernel_8336\1533519715.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  firstCry_table[col].iloc[index] = np.nan
C:\Users\TP_USER\AppData\Local\Temp\ipykernel_8336\1533519715.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  firstCry_table[col].iloc[index] = np.nan
C:\Users\TP_USER\AppData\Local\Temp\ipykernel_8336\1533519715.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  firstCry_table[col].iloc[index] = np.nan
C:\Users\TP_USER\AppData\Local\Temp\ipykernel_8336\1533519715.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  firstCry_table[col].iloc[index] = np.nan
C:\Users\TP_USER\AppData\Local\Temp\ipykernel_8336\1533519715.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  firstCry_table[col].iloc[index] = np.nan
C:\Users\TP_USER\AppData\Local\Temp\ipykernel_8336\1533519715.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  firstCry_table[col].iloc[index] = np.nan
C:\Users\TP_USER\AppData\Local\Temp\ipykernel_8336\1533519715.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  firstCry_table[col].iloc[index] = np.nan
C:\Users\TP_USER\AppData\Local\Temp\ipykernel_8336\1533519715.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  firstCry_table[col].iloc[index] = np.nan

In [6]:
firstCry_table.columns

Index(['Sr.No.', 'HSNCode', 'FCID', 'Manufacturer', 'StyleCode', 'Image',
       'Product ProductName Description', 'Unnamed: 0', 'BrandName', 'Size',
       'Color', 'MRP', 'OfferMRP', 'BaseCost', 'Tax', 'LandingRate',
       'BilledQty', 'FreeQty.0', 'TotalQty', 'Total.1Amount'],
      dtype='object')

In [7]:
firstCry_table.dropna(how='all', inplace=True)

In [8]:
import pandas as pd

for index, row in firstCry_table.iterrows():
    for nextIndex, nextRow in firstCry_table.iterrows():
        if index < nextIndex:
            if not pd.isna(nextRow['Sr.No.']):
                break
            for col in firstCry_table.columns[1:]:
                if not pd.isna(nextRow[col]):
                    firstCry_table.at[index, col] = str(firstCry_table[col][index]) +" "+ str(nextRow[col])
                    firstCry_table.at[nextIndex, col] = np.nan
                    
                    

firstCry_table.dropna(how='all', inplace=True)

In [9]:
def format_dataframes(firstCry_df):
    for col in firstCry_df.columns.tolist():
        column = col
        for index in range(len(firstCry_df[col])):
            if not pd.isna(firstCry_df[col].iloc[index]):
                column += str(firstCry_df[col].iloc[index])
                firstCry_df[col].iloc[index] = np.nan
            else:
                break
        firstCry_df.rename(columns={col: column}, inplace=True)
    firstCry_df.dropna(how='all', inplace=True)
    for index, row in firstCry_df.iterrows():
        for nextIndex, nextRow in firstCry_df.iterrows():
            if index < nextIndex:
                if not pd.isna(nextRow['Sr.No.']):
                    break
                for col in firstCry_df.columns[1:]:
                    if not pd.isna(nextRow[col]):
                        firstCry_df.at[index, col] = str(firstCry_df[col][index]) +" "+ str(nextRow[col])
                        firstCry_df.at[nextIndex, col] = np.nan
    firstCry_df.dropna(how='all', inplace=True)
    return firstCry_df

In [10]:
# dfs = [firstCry_pdf[1],firstCry_pdf[2],firstCry_pdf[3]]
# returned_dfs = []
# for df in dfs:
#     returned_dfs.append(format_dataframes(df))
# first_cry_merge = pd.concat(returned_dfs)
# first_cry_merge

In [11]:
firstCry_pdf[1]

,Sr.,HSN,FCID,Manufa,Style,Image,Product Product,Unnamed: 0,Brand,Siz,Col,MRP,Offer,Base,Tax,Landing,Bill,Fre,Total,Total.1
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1,9619,41948.0,8901138,70017,NaN,Himalay 8 to 14,NaN,Himalay,Lar,9F9,130.0,130.00,81.25,12.0,91.00,24,NaN,24,2184.00
4,NaN,NaN,4.0,831189,92,NaN,"a Herbal Kg, 9",NaN,a,ge,2B,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,"Baby pieces,",NaN,Babycar,NaN,E,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN,Diapers With anti,NaN,e,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,NaN,NaN,NaN,Large - 9 rash,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,NaN,NaN,NaN,NaN,NaN,Pieces shield,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,NaN,NaN,NaN,NaN,NaN,and,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,NaN,NaN,NaN,NaN,NaN,NaN,buttery,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,NaN,NaN,NaN,NaN,NaN,NaN,soft,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,NaN,NaN,NaN,NaN,NaN,NaN,inner,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,NaN,NaN,NaN,NaN,NaN,NaN,layer,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,2,9619,58630.0,8901138,70020,NaN,Himalay Upto 7,NaN,Himalay,Sm,9F9,650.0,650.00,406.25,12.0,455.00,24,0,24,10920.00
15,NaN,NaN,0.0,832698,48,NaN,"a Herbal kg, 0 to",NaN,a,all,2B,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,NaN,NaN,NaN,NaN,NaN,NaN,Baby 3,NaN,Babycar,NaN,E,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,NaN,NaN,NaN,NaN,NaN,NaN,"Diapers Months,",NaN,e,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,NaN,NaN,NaN,NaN,NaN,NaN,Small - Diapers,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,NaN,NaN,NaN,NaN,NaN,NaN,54 with,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,NaN,NaN,NaN,NaN,NaN,NaN,Pieces natural,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,NaN,NaN,NaN,NaN,NaN,NaN,anti rash,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,NaN,NaN,NaN,NaN,NaN,NaN,shield:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,NaN,NaN,NaN,NaN,NaN,NaN,Indian,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,NaN,NaN,NaN,NaN,NaN,NaN,Aloe and,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,NaN,NaN,NaN,NaN,NaN,NaN,Yashad,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,NaN,NaN,NaN,NaN,NaN,NaN,Bhasma,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,NaN,NaN,NaN,NaN,NaN,NaN,(Zinc,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,NaN,NaN,NaN,NaN,NaN,NaN,"Oxide),B",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,NaN,NaN,NaN,NaN,NaN,NaN,uttery,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,NaN,NaN,NaN,NaN,NaN,NaN,soft,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,NaN,NaN,NaN,NaN,NaN,NaN,inner,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,NaN,NaN,NaN,NaN,NaN,NaN,layer for,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,NaN,NaN,NaN,NaN,NaN,NaN,soft and,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,NaN,NaN,NaN,NaN,NaN,NaN,sensitive,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,NaN,NaN,NaN,NaN,NaN,NaN,skin,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
firstCry_pdf[2]

,Sr.,HSN,FCID,Manufa,Style,Image,Product,Product.1,Brand,Siz,Col,MRP,Offer,Base,Tax,Landing,Bill,Fre,Total,Total.1
0,No.,Code,NaN,cturer,Code,NaN,Name,Descript,Name,e,or,NaN,MRP,Cost,NaN,Rate,ed,e,Qty,Amount
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ion,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Qty,Qty,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,.,NaN,NaN
3,3,9619,22195.0,8901138,70027,NaN,Himalay,Upto 7,Himalay,Sm,AB,125.0,125.00,78.13,12.0,87.51,24,0,24,2100.13
4,NaN,NaN,83.0,837174,45,NaN,a Herbal,"kg, 0 to",a,all,A0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60,NaN,NaN,NaN,NaN,NaN,NaN,NaN,inner,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
61,NaN,NaN,NaN,NaN,NaN,NaN,NaN,layer for,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
62,NaN,NaN,NaN,NaN,NaN,NaN,NaN,soft and,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
63,NaN,NaN,NaN,NaN,NaN,NaN,NaN,sensitive,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
64,NaN,NaN,NaN,NaN,NaN,NaN,NaN,skin,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN